name: Deploy Next.js site to VPS

on:
  push:
    branches: [ "main" ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4

    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Lint the code
    - name: Run linting
      run: npm run lint || true

    # Build the project
    - name: Build
      run: npm run build
      
    # Create .env file if needed
    - name: Create production env file
      run: |
        echo "${{ secrets.PRODUCTION_ENV }}" > .env.production
      
    # Install SSH key
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        if_key_exists: replace

    # Deploy to VPS
    - name: Deploy to VPS
      run: |
        # Create a tar archive of the build directory
        tar -czf build.tar.gz .next public package.json package-lock.json next.config.ts .env.production
        
        # Copy files to VPS
        scp build.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/tshop-fe/
        
        # SSH into server and deploy
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/tshop-fe && \
          tar -xzf build.tar.gz && \
          npm ci --production && \
          pm2 restart tshop-fe || pm2 start npm --name tshop-fe -- start"
